### ISSUE TITLE
support for Windows on ARM

### ISSUE THREAD

**Issue by tdivoll** [AaronJCorcoran/ThruTracker#3]
Testing the install via a Windows VM on Mac with the M1 chip.

* Used `Parallels` software to install Windows 11 (Windows on ARM version) 
* Not tested on Mac without M1 chip 
* Received the following error: 
<img width="437" alt="image" src="https://user-images.githubusercontent.com/24841909/183947062-ad421c4f-3a2e-4c49-bbf0-ad9cf59ea58d.png">

* System config: 
<img width="569" alt="image" src="https://user-images.githubusercontent.com/24841909/183948141-43752a59-6a07-4715-9a19-4a840a9d5b11.png">

**Comment by tdivoll** [comment]
**Solution:**  
* Installed Microsoft Visual C++ 2015 Redistributable Update 3 RC on the Windows side (`vc_redist.x64`)
* Installed ThruTracker as expected from there

**Comment by AaronJCorcoran** [comment]
Awesome, I’ll add that to the help page!!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
